import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { GrainyFilter } from "@/src/components/Grainy";
import PageHeader from "@/src/components/Page.Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`relative ${inter.className}`}>
        <PageHeader />
        <div aria-hidden="true" className="invisible absolute">
          <GrainyFilter />
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
